### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by kingdavid72** [haanjack/mnist-cudnn#1]
#obj directory is not in the source file
SRC =  src
OBJ_DIR = obj
so instead Makefile create directory
$(shell   mkdir -p $(obj))
which is slow process
it would be better to put obj directory like src directory
simple fix is mkdir obj ^^

**Comment by haanjack** [comment]
Thanks for the suggestion :)

I prefer not to include objects which can be automatically generated.
So, I put the "@mkdir -p $(@D)" followed by "${OBJ_DIR}/train.o: train.cpp ${INCS}."

Whether it is slow or not, it would be okay now. Thanks ^^
