### ISSUE TITLE
Compile error on cuDNN v8

### ISSUE THREAD

**Issue by xTayEx** [haanjack/mnist-cudnn#6]
When compiling on cuDNN v8.7, the following compilation error occurs.
```bash

convolution.cu(82): error: identifier "CUDNN_CONVOLUTION_FWD_PREFER_FASTEST" is undefined

convolution.cu(82): error: identifier "cudnnGetConvolutionForwardAlgorithm" is undefined

convolution.cu(87): error: identifier "CUDNN_CONVOLUTION_BWD_FILTER_PREFER_FASTEST" is undefined

convolution.cu(87): error: identifier "cudnnGetConvolutionBackwardFilterAlgorithm" is undefined

convolution.cu(92): error: identifier "CUDNN_CONVOLUTION_BWD_DATA_PREFER_FASTEST" is undefined

convolution.cu(92): error: identifier "cudnnGetConvolutionBackwardDataAlgorithm" is undefined

6 errors detected in the compilation of "convolution.cu".
make: *** [Makefile:43: convolution] Error 1
```

**Comment by onlyone2019** [comment]
Hi, have you solved the problem?

**Comment by onlyone2019** [comment]
This may because after cuda 8.0 these functions have been removed.

**Comment by haanjack** [comment]
Hi, sorry for the confusion.

Although the message show some error in build, `train` is build and you can test.

The error message is limited to `convolution.cu` file and it is not related to the major software.

I updated `Makefile` so that the message will not be shown as I drop the build of `convolution.cu` file.

**Comment by xTayEx** [comment]
> Hi, sorry for the confusion.
> 
> Although the message show some error in build, `train` is build and you can test.
> 
> The error message is limited to `convolution.cu` file and it is not related to the major software.
> 
> I updated `Makefile` so that the message will not be shown as I drop the build of `convolution.cu` file.

Thanks! I just realized that the `train` has been built and I can now train the model normally
